openapi: 3.0.0
info:
  title: Roadya API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://185.105.225.38/v1
    description: Poduction server
  #- url: http://staging-api.example.com
  #  description: Optional server description, e.g. Internal staging server for testing
paths:
  /placemarks:
    # -------------- POST PLACEMARK START ---------------------- #
    post:
      summary: Добавление нового заведения
      #description: Optional extended description in CommonMark or HTML.
      requestBody:
        content:
          multipart/form-data: # Media type
            schema: # Request payload
              type: string
              example: '
              Accept: application/json
              Content-Type: multipart/form-data;boundary=Boundary

              --Boundary
              Content-Disposition: form-data; name="images[]"; filename="Koala.jpg"
              Content-Type: image/jpeg

              < Koala.jpg

              --Boundary
              Content-Disposition: form-data; name="images[]"; filename="image1.jpg"
              Content-Type: image/jpeg

              < Lighthouse.jpg

              --Boundary
              Content-Disposition: form-data; name="data"
              Content-Type: application/json

              {
                "name": "Test placemark2222",
                "address": "Санкт-Петербург; Невский, 22222",
                "url": "https://test222.com",
                "phone": "+79112223344",
                "instagram": "o.nurutdinov",
                "telegram": "o.nurutdinov",
                "whatsapp": "+79112223344",
                "vk": "https://vk.com/id1748231",
                "viber": "+79112223344",
                "point": "37.884929 -122.429415",
                "tags": "[cargo, passenger]"
              }

              --Boundary
              ###'

      responses:
        '201': # status code
          description: Created
          content:
            application/json:
              example:
                status: success
                message: Заведение успешно создано.
                data:
                  id: 1
                  name: Test placemark2222
                  address: Санкт-Петербург; Невский, 22222
                  url: https://test222.com,
                  phone: +79112223344
                  instagram: o.nurutdinov
                  telegram: o.nurutdinov
                  whatsapp: +79112223344
                  vk: https://vk.com/id1748231
                  viber: +79112223344
                  point: [ 37.884929, -122.42941 ]
                  user_id: 1

    get:
      summary: Получение списка заведений
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Номер страницы
        - in: query
          name: count
          schema:
            type: integer
          description: Количество заведений на странице
        - in: query
          name: polygon
          schema:
            type: array
            items:
              type: string
            example: [['37.884929', '-122.429415'], ['37.884929', '-122.429415'], ['37.884929', '-122.429415']]
          description: Координаты полигона, в котором необходимо найти заведения
      responses:
        '200': # status code
          description: OK
          content:
            application/json:
              example:
                status: success
                message: ''
                data:
                  current_page: 1
                  data:
                    [
                      {
                        "id": 2,
                        "name": "Test placemark",
                        "address": "Санкт-Петербург; Невский, 11",
                        "url": "https://test.com",
                        "phone": "+79112223344",
                        "instagram": "o.nurutdinov",
                        "telegram": "o.nurutdinov",
                        "whatsapp": "+79112223344",
                        "vk": "https://vk.com/id1748231",
                        "viber": "+79112223344",
                        "point": [
                            37.774929,
                            -122.419415
                        ],
                        "created_at": "2020-12-15T14:22:16.000000Z",
                        "updated_at": "2020-12-15T14:22:16.000000Z",
                        "user_id": 1,
                        "latitude": 37.774929,
                        "longitude": -122.419415,
                        "reviews_rating": "4.5000",
                        "images": [
                          {
                            "id": 1,
                            "path": "/storage/placemarks/2/PHCADfPw2iIyOGLhg1biDNLqaPGMAEQk5fLzYgF9.jpeg",
                            "imagable_type": "App\\Models\\Placemark",
                            "imagable_id": 2
                          },
                          {
                            "id": 2,
                            "path": "/storage/placemarks/2/fTwdUAqIecjA19jXH15TBpL1qUHXW106ls05kYKT.jpeg",
                            "imagable_type": "App\\Models\\Placemark",
                            "imagable_id": 2
                          }
                        ],
                        "rating": [
                          {
                            "rating": "4.5000",
                            "placemark_id": 2
                          }
                        ],
                        "tags": [ {
                          "id": 2,
                          "code": "interesting",
                          "name": "Интересное",
                          "pivot": {
                            "placemark_id": 2,
                            "tag_id": 2
                          }
                        },
                          {
                            "id": 5,
                            "code": "big_transport_parking",
                            "name": "Парковка для большого транспорта",
                            "pivot": {
                              "placemark_id": 2,
                              "tag_id": 5
                            }
                          }]
                      },
                      {
                        "id": 3,
                        "name": "Test placemark2222",
                        "address": "Санкт-Петербург; Невский, 22222",
                        "url": "https://test222.com",
                        "phone": "+79112223344",
                        "instagram": "o.nurutdinov",
                        "telegram": "o.nurutdinov",
                        "whatsapp": "+79112223344",
                        "vk": "https://vk.com/id1748231",
                        "viber": "+79112223344",
                        "point": [
                            37.884929,
                            -122.429415
                        ],
                        "created_at": "2020-12-15T18:18:53.000000Z",
                        "updated_at": "2020-12-15T18:18:53.000000Z",
                        "user_id": 1,
                        "latitude": 37.884929,
                        "longitude": -122.429415,
                        "reviews_rating": "4.0000",
                        "images": [
                          {
                            "id": 3,
                            "path": "/storage/placemarks/3/HQGEusX1UKjk8eune6yQtIl7inSrQEdEWB8zTXkh.jpeg",
                            "imagable_type": "App\\Models\\Placemark",
                            "imagable_id": 3
                          },
                          {
                            "id": 4,
                            "path": "/storage/placemarks/3/58UxVUoECtGOUlldcWNqHZqlL7dWM1DBMMzugZFf.jpeg",
                            "imagable_type": "App\\Models\\Placemark",
                            "imagable_id": 3
                          }
                        ],
                        "rating": [
                          {
                            "rating": "4.0000",
                            "placemark_id": 3
                          }
                        ],
                        "tags": [ ]
                      }
                    ]
                  first_page_url: http://127.0.0.1:8000/api/placemarks?page=2
                  from: 1
                  next_page_url: http://127.0.0.1:8000/api/placemarks?page=3
                  path: http://127.0.0.1:8000/api/placemarks
                  per_page: 10
                  prev_page_url: http://127.0.0.1:8000/api/placemarks?page=1
                  to: 2


  /placemarks/{id}:
    put:
      summary: Обновление заведения
      parameters:
        - in: path
          name: id   # Note the name is the same as in the path
          required: true
          schema:
            type: integer
            minimum: 1
          description: ID заведения
      #description: Optional extended description in CommonMark or HTML.
      requestBody:
        content:
          multipart/form-data: # Media type
            schema: # Request payload
              type: string
              example: '
                  Accept: application/json
                  Content-Type: multipart/form-data;boundary=Boundary

                  --Boundary
                  Content-Disposition: form-data; name="images[]"; filename="Koala.jpg"
                  Content-Type: image/jpeg

                  < Koala.jpg

                  --Boundary
                  Content-Disposition: form-data; name="images[]"; filename="image1.jpg"
                  Content-Type: image/jpeg

                  < Lighthouse.jpg

                  --Boundary
                  Content-Disposition: form-data; name="data"
                  Content-Type: application/json

                  {
                    "name": "Test placemark2222",
                    "address": "Санкт-Петербург; Невский, 22222",
                    "url": "https://test222.com",
                    "phone": "+79112223344",
                    "instagram": "o.nurutdinov",
                    "telegram": "o.nurutdinov",
                    "whatsapp": "+79112223344",
                    "vk": "https://vk.com/id1748231",
                    "viber": "+79112223344",
                    "point": "37.884929 -122.429415",
                    "tags": "[cargo, passenger]",
                    "delete_images": [1, 2]
                  }

                  --Boundary
                  ###'
      responses:
        '200': # status code
          description: OK
          content:
            application/json:
              example:
                status: success
                message: ''
                data:
                  id: 1
                  name: Test placemark2222
                  address: Санкт-Петербург; Невский, 22222
                  url: https://test222.com,
                  phone: +79112223344
                  instagram: o.nurutdinov
                  telegram: o.nurutdinov
                  whatsapp: +79112223344
                  vk: https://vk.com/id1748231
                  viber: +79112223344
                  point: [ 37.884929, -122.42941 ]
                  user_id: 1
    # -------------- PUT PLACEMARK END ---------------------- #

    # -------------- DELETE PLACEMARK START ---------------------- #
    delete:
      summary: Удаление заведения
      parameters:
        - in: path
          name: id   # Note the name is the same as in the path
          required: true
          schema:
            type: integer
            minimum: 1
          description: ID заведения

      responses:
        '200': # status code
          description: OK
          content:
            application/json:
              example:
                status: success
                message: 'Заведение успешно удалено'
                data: []
    # -------------- DELETE PLACEMARK END ---------------------- #

components:
  schemas:
    Placemark:
      properties:
        id:
          type: integer
          example: 0
        name:
          type: string
          example: 'name'
        address:
          type: string
          example: 'address'
        url:
          type: string
          example: 'test.com'
        phone:
          type: string
          example: '+79991112233'
        instagram:
          type: string
          example: 'sssss'
